![image.png](attachment:image.png)

# Numpy

Numpy is THE library for scientific computing and linear algebra in Python's community and was designed to give users the best of both worlds in programming languages: the speed of `C` language with the readability and elegance of `Python`.

### Why Numpy?
A question arises that why do we need NumPy when python lists are already there. The answer to it is we cannot perform operations on all the elements of two list directly. For example we cannot multiply two lists directly we will have to do it element wise. This is where the role of NumPy comes into play.

In [26]:
from numpy import *
import numpy as np

Very quick speed comparison to show the staggering difference in performance, don't bother about the code in the following cell.

In [27]:
import numpy as np
import time
import gc # garbage collection
import sys


def compare_times(f1, f2, setup1=None, setup2=None, runs=30):
    print('    format: mean seconds (standard error)', runs, 'runs')
    maxpad = max(len(f.__name__) for f in (f1, f2))
    means = []
    for setup, f in [[setup1, f1], [setup2, f2]]:
        setup = (lambda: tuple()) if setup is None else setup
        
        total_times = []
        for _ in range(runs):
            try:
                gc.disable()
                args = setup()
                
                start = time.time()
                if isinstance(args, tuple):
                    f(*args)
                else:
                    f(args)
                end = time.time()
                
                total_times.append(end - start)
            finally:
                gc.enable()
                
        mean = np.mean(total_times)
        se = np.std(total_times) / np.sqrt(len(total_times))
        print('    {} {:.2e} ({:.2e})'.format(f.__name__.ljust(maxpad), mean, se))
        means.append(mean)
    print('    improvement ratio {:.1f}'.format(means[0] / means[1]))

In [28]:
size = 10 ** 7 
print('create a list 1, 2, ...', size)


def create_list(): return list(range(size))
def create_array(): return np.arange(size, dtype=int)

compare_times(create_list, create_array)

create a list 1, 2, ... 10000000
    format: mean seconds (standard error) 30 runs
    create_list  4.04e-01 (2.19e-02)
    create_array 1.92e-02 (1.14e-03)
    improvement ratio 21.0


In [29]:
import time
num = 10000000
a = np.random.random(num)
b = np.random.random(num)

star = time.time()
c = np.dot(a,b)
en = time.time()
print(c)
print("Verctorize  : " +  str((en -star)*1000) + 'ms')

d =0
start = time.time()
for i in range(num):
    d += a[i]*b[i]
end = time.time()

print(d)
print("Loop version  : " +  str((end -start)*1000) + 'ms')
print("Vectorization is faster by" , (end -start)/(en -star) , 'times')

2499730.9203768764
Verctorize  : 1312.0841979980469ms
2499730.9203765444
Loop version  : 6767.758131027222ms
Vectorization is faster by 5.158021216438197 times


### Convinced about numpy powers? ... Now, let's practice!

In [1]:
import numpy as np

#### Q1: Create a 1D array of numbers from 0 to 9.


In [2]:
arr = np.array([i for i in range(10)])

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(0 , 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Q2: Extract all odd numbers from arr.


In [6]:
np.arange(1 , 10 , 2)

array([1, 3, 5, 7, 9])

In [7]:
arr[arr%2 !=0 ]

array([1, 3, 5, 7, 9])

In [9]:
arr[arr%2 == 1 ]

array([1, 3, 5, 7, 9])

In [8]:
arr[arr > 3]

array([4, 5, 6, 7, 8, 9])

#### Q3: Replace all odd numbers in arr with -1.


In [10]:
arr[arr %2 == 1 ] = -1

In [12]:
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

#### Q4: Convert a 1D array of length 10 to a 2D array with 2 rows


In [13]:
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [14]:
arr.reshape(2 , 5)

array([[ 0, -1,  2, -1,  4],
       [-1,  6, -1,  8, -1]])

In [17]:
arr.reshape(1 ,10)

array([[ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1]])

In [18]:
arr.reshape(10 , 1)

array([[ 0],
       [-1],
       [ 2],
       [-1],
       [ 4],
       [-1],
       [ 6],
       [-1],
       [ 8],
       [-1]])

In [20]:
arr.reshape(5 , 2)

array([[ 0, -1],
       [ 2, -1],
       [ 4, -1],
       [ 6, -1],
       [ 8, -1]])

#### Q5: compute the square root for each element in the  array
#### ([[1, 2, 3],[2, 3, 4],[4, 5, 6]])


In [22]:
lst = [
    [1, 2, 3],
    [2, 3, 4],
    [4, 5, 6]
]

In [23]:
mtrix = np.array(lst)

In [24]:
mtrix

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [25]:
np.sqrt(mtrix)

array([[1.        , 1.41421356, 1.73205081],
       [1.41421356, 1.73205081, 2.        ],
       [2.        , 2.23606798, 2.44948974]])

#### Q6: compute the exponential for each element in the above array


In [26]:
np.exp(mtrix)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [  7.3890561 ,  20.08553692,  54.59815003],
       [ 54.59815003, 148.4131591 , 403.42879349]])

#### Q7: sample 8 elements from uniform dist ([0, 1)


In [28]:
np.random.uniform(0 , 1 , 8)

array([0.23748736, 0.5706163 , 0.53178622, 0.24264844, 0.93075273,
       0.42864001, 0.54691061, 0.88118002])

#### Q8: Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10.

In [50]:
np.random.rand(8)

array([0.76722594, 0.83778766, 0.78257018, 0.83836979, 0.11123933,
       0.04504759, 0.77758028, 0.09151119])

In [32]:
np.random.randint(3)

0

In [ ]:
np.random.randint(0 , 10)

In [46]:
for i in range(100):
    print(np.random.randint(0 , 2 , 2))

[1 0]
[1 1]
[0 0]
[0 0]
[1 0]
[1 1]
[0 0]
[1 1]
[1 0]
[0 0]
[1 0]
[0 1]
[1 1]
[1 0]
[0 1]
[1 0]
[1 0]
[0 1]
[1 0]
[0 1]
[1 0]
[1 1]
[0 0]
[0 0]
[1 0]
[1 1]
[1 1]
[1 0]
[0 1]
[0 1]
[0 0]
[0 1]
[1 1]
[1 1]
[1 0]
[1 0]
[0 1]
[1 1]
[0 1]
[1 0]
[1 1]
[1 0]
[0 1]
[1 0]
[0 1]
[0 1]
[0 0]
[1 1]
[1 1]
[0 0]
[0 0]
[1 0]
[0 1]
[0 1]
[0 0]
[1 0]
[0 1]
[1 1]
[1 0]
[1 1]
[0 1]
[1 1]
[1 0]
[1 0]
[1 1]
[1 0]
[1 0]
[1 1]
[1 0]
[0 0]
[1 1]
[1 1]
[1 0]
[1 0]
[1 0]
[0 1]
[0 1]
[0 0]
[1 1]
[1 1]
[1 0]
[1 1]
[1 0]
[1 0]
[1 1]
[1 0]
[1 0]
[1 1]
[0 0]
[1 0]
[1 1]
[1 0]
[0 0]
[1 0]
[1 1]
[1 0]
[1 0]
[0 0]
[1 0]
[0 0]


#### Q9: Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21

In [72]:
[range(10 , 20)]

[range(10, 20)]

In [73]:
np.array(range(10 , 22)).reshape(3 ,4)

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [59]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [67]:
np.arange(10 ,22).reshape(3,4)

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [65]:
np.random.randint(10 , 22 , size = (3 ,4))

array([[19, 11, 21, 10],
       [16, 10, 15, 20],
       [21, 12, 14, 11]])

#### Q10: Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50.

In [74]:
np.linspace(5 , 50 , 10)

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

In [77]:
np.linspace(5 , 50 , 10).reshape(10 , 1)

array([[ 5.],
       [10.],
       [15.],
       [20.],
       [25.],
       [30.],
       [35.],
       [40.],
       [45.],
       [50.]])

#### Q11: Write a NumPy program to create an array of all the even integers from 30 to 70.

In [79]:
np.arange(30 , 71 , 2 )

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

#### Q12: Write a NumPy program to check whether two arrays are equal (element wise) or not

In [92]:
lst = [2,3,4]
lst1 = [2,3,4]

In [99]:
len(lst)

3

In [109]:
i = j = counter = 0
while i < len(lst) and lst[i] == lst1[j]:
    i += 1 
    j += 1 
    counter += 1 
    
    
    
if counter == len(lst):
    print('=')
else : 
    print('!=')

=


In [111]:
counter = 0
if len(lst) == len(lst1):
    
    for i,j in zip(lst , lst1):

        if i == j:
            counter += 1 
    print('==' if counter == len(lst) else '!=')
    
    
else :
    print('!=')
    
    

==


# search on this line of code 

In [114]:
len(lst) == len(lst1) and all(x == y for x, y in zip(lst, lst1))

True

In [112]:
arr = np.array([2,3,4])
arr1 = np.array([2,3,4])

In [113]:
arr == arr1

array([ True,  True,  True])

In [115]:
np.array_equal(arr , arr1)

True

* further reading: [visit here](https://www.w3resource.com/python-exercises/numpy/index.php)

In [116]:
np.load('matrix.npy')

array([[28, 30, 79, 90, 90, 71, 68, 72, 79, 91],
       [33, 15, 46, 87, 66, 16, 86, 63, 56, 40],
       [45, 58, 90, 10, 36, 38, 88, 89, 96, 83],
       [71, 19, 92, 35, 21, 84, 27, 32, 71, 51],
       [23, 58, 58, 83, 82, 93, 45, 64, 79, 77],
       [81, 60, 13, 77, 57, 11, 50, 70, 11, 82],
       [85, 89, 62, 29, 19, 81, 10, 14, 64, 77],
       [94, 16, 55, 11, 71, 45, 43, 30, 98, 39],
       [76, 97, 60, 24, 45, 68, 57, 53, 21, 59],
       [34, 35, 61, 35, 22, 38, 75, 40, 35, 43]])